# Generated by Django 4.2.4 on 2024-08-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='registration',
        ),
    ]
